# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1
orbs:
  node: circleci/node@4.7
  cypress:cypress-io/cypress@9.7.0
workflows:
    jobs:
    - cypress/run
      - node/test:
          version: '16.10'
          pkg-manager: npm

